### ISSUE TITLE
Verständnisfrage

### ISSUE THREAD

**Issue by MarcusCaepio** [bodsch/icinga2-notification-telegram#1]
Hallo bodsch,
ich habe deinen Blogeintrag gelesen und finde die Lösung echt charmant. Habe dazu aber Verständnisfragen.
In dem Script gibst du die Variable USERTELEGRAM an. Da ich mich bisher noch gar nicht mit Telegram beschäftigt habe, ist das die ChatID zwischen mir und dem Bot oder meine Telegram ID?
Wo definierst du den Wert dieser Variable? Ist es möglich, per telegram auch alarme an mehrere User zu schicken?

Danke im Vorfeld

Gruß

Marcus

**Comment by bodsch** [comment]
Die Variable USERTELEGRAM wird im Object NotificationCommand gepflegt.
Ähnlich wie die Variablen für SMS Alarmierungen.

Als Beispiel eine funktionierende notification.conf:

```
object NotificationCommand "telegram-service-notification" {
  import "plugin-notification-command"

  command = [ SysconfDir + "/icinga2/scripts/telegram-service-notification.sh" ]

  env += {
    "HOSTADDRESS" = "$address$"
    "HOSTALIAS" = "$host.display_name$"
    "HOSTDISPLAYNAME" = "$host.display_name$"
    "LONGDATETIME" = "$icinga.long_date_time$"
    "NOTIFICATIONAUTHORNAME" = "$notification.author$"
    "NOTIFICATIONCOMMENT" = "$notification.comment$"
    "NOTIFICATIONTYPE" = "$notification.type$"
    "SERVICEDESC" = "$service.name$"
    "SERVICEDISPLAYNAME" = "$service.display_name$"
    "SERVICEOUTPUT" = "$service.output$"
    "SERVICESTATE" = "$service.state$"
    "USEREMAIL" = "$user.email$"
    "USERTELEGRAM" = "$user.vars.telegram$"
  }
}
```

USERTELEGRAM sollte also deiner TelegramID entsprechen.

Die definition dieser Variablen erfolgt dann im entsprechenden User Object.

Ob man Alarme dann an mehrere User sender  ist AFAIK irrelevant, da sich mehrere User am Bot registrieren können.

Gruß,
 Bodo

**Comment by MarcusCaepio** [comment]
Hi Bodo,

danke für's Feedback.
Habe es erfolgreich mit einem Bot getestet. 

Gruß,

Marcus
